FROM node:20-alpine
WORKDIR /usr/src/app
COPY package*.json ./
# Добавляем флаг для решения конфликтов зависимостей NestJS
RUN npm install --legacy-peer-deps
COPY . .
RUN npm run build
EXPOSE 8000
CMD ["npm", "run", "start:dev"]
