import { Controller, Post, Body, Get, HttpCode, HttpStatus, Logger } from '@nestjs/common';
import { GitHubService } from '../services/github.service';

interface StartDevelopmentDto {
  developmentGoals: string[];
  maxIterations: number;
  priority: 'low' | 'medium' | 'high';
}

interface DevelopmentTask {
  taskId: string;
  status: 'queued' | 'in_progress' | 'completed';
  branch: string;
  createdAt: Date;
  developmentGoals: string[];
}

@Controller(arqv1/arq')
export class ARQController {
  private readonly logger = new Logger('ARQController');
  private taskCounter = 0;
  private activeTasks: Map<string, DevelopmentTask> = new Map();

  constructor(private readonly githubService: GitHubService) {}

  @Post('start-development')
  @HttpCode(HttpStatus.CREATED)
  async startDevelopment(@Body() dto: StartDevelopmentDto) {
    this.logger.log(`[ARQ] Starting development cycle with goals: ${dto.developmentGoals.join(', ')}`);
    
    try {
      // Generate unique task ID
      const taskId = `arq-dev-${Date.now()}-${++this.taskCounter}`;
      
      // Create development branch
      const branchName = `feature/arq-improvement-${taskId}`;
      this.logger.log(`[ARQ] Creating branch: ${branchName}`);
      
      // Initialize task
      const task: DevelopmentTask = {
        taskId,
        status: 'in_progress',
        branch: branchName,
        createdAt: new Date(),
        developmentGoals: dto.developmentGoals,
      };
      
      this.activeTasks.set(taskId, task);
      
      // Create GitHub issue for tracking
      this.logger.log(`[ARQ] Task ${taskId} created successfully`);
      
      return {
        taskId,
        status: task.status,
        branch: branchName,
        goals: dto.developmentGoals,
        message: 'Development cycle started',
        timestamp: new Date(),
      };
    } catch (error) {
      this.logger.error(`[ARQ] Error starting development: ${error.message}`);
      throw error;
    }
  }

  @Get('tasks')
  getAllTasks() {
    this.logger.log(`[ARQ] Retrieving all tasks`);
    return {
      total: this.activeTasks.size,
      tasks: Array.from(this.activeTasks.values()),
    };
  }

  @Get('tasks/:taskId')
  getTaskStatus(taskId: string) {
    this.logger.log(`[ARQ] Retrieving task status: ${taskId}`);
    const task = this.activeTasks.get(taskId);
    
    if (!task) {
      return { error: 'Task not found', taskId };
    }
    
    return task;
  }

  @Get('health')
  @HttpCode(HttpStatus.OK)
  getHealth() {
    return {
      status: 'healthy',
      timestamp: new Date(),
      activeTasks: this.activeTasks.size,
      service: 'ARQ Self-Development Engine',
    };
  }

  private generateIssueDescription(dto: StartDevelopmentDto, taskId: string): string {
    return `## ARQ Self-Development Task
\nTask ID: ${taskId}

### Development Goals
${dto.developmentGoals.map(goal => `- ${goal}`).join('\n')}

### Priority
${dto.priority.toUpperCase()}

### Details
- Auto-generated by ARQ Self-Development Engine
- Max iterations: ${dto.maxIterations}
- Created at: ${new Date().toISOString()}

### Branch
\`feature/arq-improvement-${taskId}\`

### Status
🚀 In Progress`;
  }
}
